project:
  type: website
  output-dir: docs

website:
  title: "Ethan Harner - MUSA 5080 Portfolio"
navbar:
  left:
    - href: index.qmd
      text: Home
    - text: Labs
      menu:
        - href: labs/lab_0/
          text: "Lab 0: dplyr Basics
      - href: weekly-notes/
        text: Weekly Notes

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
