project:
  type: website
  output-dir: docs

website:
  title: "Ethan Harner - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
        - href: labs/lab_0/lab0_Jan_20.qmd
          text: "Lab 0: dplyr Basics"
      # - text: Weekly Notes
      #   menu:

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
